language: php
php:
  - 7.2
matrix:
   fast_finish: true
# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - sudo apt-get update -qq

install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script: phpunit -vvv
